{% set name = "libnvjpeg" %}
{% set version = "12.4.0.16" %}
{% set cuda_version = "12.9" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/{{ name }}/{{ platform }}/{{ name }}-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 472da90f8d3dc6af9360b33b15aad0dc826fd7ff08f7d206bb2f37de1e240b64  # [linux64]
  sha256: 193388e41f8ab1faf84210c400d05fc1554a0f2d08c6b5129d53f5c2dc8ff0eb  # [aarch64]
  sha256: 7b59dd3e8da29c9cd0d871c9fbf18b9fb936dc00dd0d3f32ddb53e5bf44c4584  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]
    - patchelf <0.18.0                      # [linux]

outputs:
  - name: libnvjpeg
    files:
      - lib/libnvjpeg.so.*            # [linux]
      - targets/{{ target_name }}/lib/libnvjpeg.so.*  # [linux]
      - Library\bin\nvjpeg*.dll       # [win]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ stdlib("c") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath.sh
      commands:
        - test -L $PREFIX/lib/libnvjpeg.so.{{ version.split(".")[0] }}                            # [linux]
        - test -L $PREFIX/lib/libnvjpeg.so.{{ version }}                                          # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libnvjpeg.so.{{ version.split(".")[0] }}  # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnvjpeg.so.{{ version }}                # [linux]
        - bash test-rpath.sh                                                                      # [linux]
        - if not exist %LIBRARY_BIN%\nvjpeg64_{{ version.split(".")[0] }}.dll exit 1              # [win]
    about:
      home: https://developer.nvidia.com/nvjpeg
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: nvJPEG native runtime libraries
      description: |
        nvJPEG native runtime libraries
      doc_url: https://docs.nvidia.com/cuda/nvjpeg/index.html

  - name: libnvjpeg-dev
    build:
      run_exports:
        - {{ pin_subpackage("libnvjpeg", max_pin="x") }}
    files:
      - lib/libnvjpeg.so                                  # [linux]
      - lib/pkgconfig/nvjpeg*.pc                          # [linux]
      - targets/{{ target_name }}/lib/libnvjpeg.so        # [linux]
      - targets/{{ target_name }}/lib/stubs/libnvjpeg.so  # [linux]
      - targets/{{ target_name }}/include/nvjpeg*         # [linux]
      - Library\include                                   # [win]
      - Library\lib\nvjpeg.lib                            # [win]
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("libnvjpeg", exact=True) }}
        - cuda-cudart-dev
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - libnvjpeg-static >={{ version }}      # [linux]
    test:
      commands:
        - test -L $PREFIX/lib/libnvjpeg.so                                    # [linux]
        - test -f $PREFIX/lib/pkgconfig/nvjpeg*.pc                            # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/nvjpeg.h          # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libnvjpeg.so          # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/lib/stubs/libnvjpeg.so    # [linux]
        - if not exist %LIBRARY_INC%\nvjpeg.h exit 1                          # [win]
        - if not exist %LIBRARY_LIB%\nvjpeg.lib exit 1                        # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: nvJPEG native runtime libraries
      description: |
        nvJPEG native runtime libraries
      doc_url: https://docs.nvidia.com/cuda/nvjpeg/index.html

  - name: libnvjpeg-static
    build:
      skip: true  # [not linux]
    files:
      - targets/{{ target_name }}/lib/libnvjpeg_static.a  # [linux]
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/lib/libnvjpeg_static.a  # [linux]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: nvJPEG native runtime libraries
      description: |
        nvJPEG native runtime libraries
      doc_url: https://docs.nvidia.com/cuda/nvjpeg/index.html

about:
  home: https://developer.nvidia.com/nvjpeg
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: nvJPEG native runtime libraries
  description: |
    nvJPEG native runtime libraries
  doc_url: https://docs.nvidia.com/cuda/nvjpeg/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: libnvjpeg
